version: '3.5'
services:
  redis-slack:
    image: "bitnami/redis:latest"
    hostname: "slack-redis"
    container_name: slack-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - slack-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 2s
      retries: 10

networks:
  slack-network:
    name: slack-network
    driver: bridge